### PR TITLE
Ordered task execution

### LINKED ISSUE #900: Periodic failures due to "No such file or directory"
Playing around with deis, I noticed that sometimes when you `deis scale` up, some of the containers wouldn't launch. Digging through the logs, I found this:

```
Sep 15 18:19:17 deis-1 fleetd[579]: INFO manager.go:222: Writing systemd unit madras-stickpin_v3.cmd.10-announce.service (1235b)
Sep 15 18:19:17 deis-1 fleetd[579]: INFO reconcile.go:274: AgentReconciler completed task: type=LoadUnit job=madras-stickpin_v3.cmd.10-announce.service reason="unit scheduled here but not loaded"
Sep 15 18:19:17 deis-1 fleetd[579]: ERROR manager.go:113: Failed to start systemd unit madras-stickpin_v3.cmd.10-announce.service: Unit madras-stickpin_v3.cmd.10.service failed to load: No such file or director
y.
Sep 15 18:19:17 deis-1 fleetd[579]: INFO reconcile.go:274: AgentReconciler completed task: type=StartUnit job=madras-stickpin_v3.cmd.10-announce.service reason="unit currently loaded but desired state is launch
ed"
```

Manually calling `systemctl start madras-stickpin_v3.cmd.10-announce.service` worked fine, so clearly there's some race condition here between writing the file to disk and starting it in systemd.

### LINKED ISSUE #997: fleet can start units out of order on startup
1. `fleetctl start` the following units

```
$ cat bar.service
[Service]
ExecStart=/usr/bin/sleep infinity

$ cat foo.service
[Unit]
Requires=bar.service
After=bar.service

[Service]
ExecStart=/usr/bin/sleep infinity

[X-Fleet]
MachineOf=bar.service
```

2. `systemctl kill -s SIGKILL fleet && systemctl start fleet`

There is a chance that fleet will load and attempt to start `bar.service` before loading `foo.service`, causing the following error:

```
Oct 22 22:15:57 core-01 fleetd[6111]: ERROR manager.go:80: Failed to trigger systemd unit bar.service start: Unit foo.service failed to load: No such file or directory.
```

This bug was originally reported in https://github.com/coreos/fleet/issues/974.

### LINKED ISSUE #1003: Fleet starts units before required ones are loaded after a reboot
I'm trying to run an Elasticsearch cluster with fleet. Each ```elasticsearch@.service``` has ```-data``` & ```-discovery``` sidekicks on which the main unit has a ```Requires=```.

To get it up and running I first load all necessary units and then start the elasticsearch@.service units which in turn starts their respective sidekicks.

This works nicely except after a reboot when fleet tries to start the main service before its sidekicks are loaded:

```
Oct 24 21:32:51 core-02 fleetd[591]: INFO server.go:148: Starting server components
Oct 24 21:32:54 core-02 fleetd[591]: INFO manager.go:218: Writing systemd unit elasticsearch@3.service (1343b)
Oct 24 21:32:54 core-02 fleetd[591]: INFO manager.go:142: Instructing systemd to reload units
Oct 24 21:32:54 core-02 fleetd[591]: INFO reconcile.go:274: AgentReconciler completed task: type=LoadUnit job=elasticsearch@3.service reason="unit scheduled here but not loaded"
Oct 24 21:32:54 core-02 fleetd[591]: ERROR manager.go:80: Failed to trigger systemd unit elasticsearch@3.service start: Unit elasticsearch-data@3.service failed to load: No such file or directory.
Oct 24 21:32:54 core-02 fleetd[591]: INFO reconcile.go:274: AgentReconciler completed task: type=StartUnit job=elasticsearch@3.service reason="unit currently loaded but desired state is launched"
Oct 24 21:32:59 core-02 fleetd[591]: INFO manager.go:218: Writing systemd unit elasticsearch-data@3.service (370b)
Oct 24 21:32:59 core-02 fleetd[591]: INFO manager.go:142: Instructing systemd to reload units
Oct 24 21:32:59 core-02 fleetd[591]: INFO manager.go:218: Writing systemd unit elasticsearch-discovery@3.service (515b)
Oct 24 21:32:59 core-02 fleetd[591]: INFO reconcile.go:274: AgentReconciler completed task: type=LoadUnit job=elasticsearch-data@3.service reason="unit scheduled here but not loaded"
Oct 24 21:32:59 core-02 fleetd[591]: INFO manager.go:142: Instructing systemd to reload units
Oct 24 21:32:59 core-02 fleetd[591]: INFO reconcile.go:274: AgentReconciler completed task: type=LoadUnit job=elasticsearch-discovery@3.service reason="unit scheduled here but not loaded"
```

To reproduce this follow the instructions from [here](https://gist.github.com/digital-wonderland/e0bd8e0d4c91a7fec2c7#usage). After the cluster is up restart one of the hosts.

My uneducated guess would be that deployment should first load all units, which are scheduled for a host, before trying to start one of them.

This also seems to be similar to #997 except that here sidekicks get only loaded but not started (since the ```Requires=``` in the main unit takes care of that).

### LINKED ISSUE #1127: Fleet unit uploaded, yet missing
Hi

CoreOS 584.0.0

fleetctl destroy wordpress-sidekick.service
fleetctl start wordpress-sidekick.service

or:
destroy - submit - load - start, 

Expected result: unit will run
Actual result: unit is failed

Logs from fleet:

```
Feb 11 08:17:16 ip-10-0-4-135.ec2.internal fleetd[613]: ERROR manager.go:147: Failed to trigger systemd unit wordpress-sidekick.service stop: Unit wordpress-sidekick.service not loaded.
Feb 11 08:17:16 ip-10-0-4-135.ec2.internal fleetd[613]: INFO manager.go:275: Removing systemd unit wordpress-sidekick.service
Feb 11 08:17:16 ip-10-0-4-135.ec2.internal fleetd[613]: INFO reconcile.go:321: AgentReconciler completed task: type=UnloadUnit job=wordpress-sidekick.service reason="unit loaded but not scheduled here"
Feb 11 08:18:26 ip-10-0-4-135.ec2.internal fleetd[613]: INFO manager.go:262: Writing systemd unit wordpress-sidekick.service (740b)
Feb 11 08:18:26 ip-10-0-4-135.ec2.internal fleetd[613]: INFO reconcile.go:321: AgentReconciler completed task: type=LoadUnit job=wordpress-sidekick.service reason="unit scheduled here but not loaded"
Feb 11 08:18:58 ip-10-0-4-135.ec2.internal fleetd[613]: ERROR manager.go:136: Failed to trigger systemd unit wordpress-sidekick.service start: Unit wordpress-sidekick.service failed to load: No such file or directory.
Feb 11 08:18:58 ip-10-0-4-135.ec2.internal fleetd[613]: INFO reconcile.go:321: AgentReconciler completed task: type=StartUnit job=wordpress-sidekick.service reason="unit currently loaded but desired state is launched"
```

unit file details:
Wants=etcd.service
After=etcd.service

BindsTo=wordpress.service
After=wordpress.service

Restart=always

(wordpress and etcd units are up and running)

### PR DESCRIPTION
**Pull request by bcwaldon**
On master, a given fleet agent reconciles its current state against the desired state by generating a set of taskChain objects. A taskChain is a series of tasks that should be executed against a given unit. For example, a new unit is started on an agent with a taskChain containing a LoadUnit and a StartUnit task. A unit file is replaced with a chain of UnloadUnit, LoadUnit, StartUnit. The flaw here, however, is that there isn't any ordering between the execution of the taskChains themselves. So if you have unit foo.service that BindsTo bar.service, fleet will race to start them both, and sometimes foo.service will fail with "No such file or directory" since bar.service may not have actually been written to disk yet.

The alternative proposed here is to throw the taskChain concept out the window in favor of an ordered set of tasks, where each task is executed in serial. Before starting execution, the tasks are sorted such that all LoadUnit tasks are executed before StartUnit tasks. This fixes the "No such file or directory" problems many folks have been running into by making sure all unit files are available on disk before taking any actions on them. The loss of concurrency should not be an issue as fleet already uses the DBus APIs for job control and doesn't actually block on completion.

Fix #900 
Fix #997 
Fix #1003 
Fix #1127

### CODE REVIEW

File: agent/reconcile.go [hunk 1]
```diff
@@ -275,51 +270,45 @@ func (ar *AgentReconciler) calculateTaskChainForUnit(dState *AgentState, cState
...
 
-func (ar *AgentReconciler) launchTaskChain(tc taskChain, a *Agent) {
-	log.Debugf("AgentReconciler attempting task chain %s", tc)
-	reschan, err := ar.tManager.Do(tc, a)
-	if err != nil {
-		log.Infof("AgentReconciler task chain failed: chain=%s err=%v", tc, err)
-		return
-	}
-
-	go func() {
```
Comment (philips) [inline agent/reconcile.go]: why is it now safe to get rid of the go routine here?

Comment (bcwaldon) [inline agent/reconcile.go]: It's sort of a long story. The short version is that it used to be safe to spin off a goroutine here because the TaskManager would reject new taskChains for units that already have work in progress. Now that the TaskManager does not track the in-flight tasks (and therefore is no longer threadsafe), the reconciler should not interact with the TaskManager concurrently (which this goroutine would allow).

Comment (bcwaldon) [inline agent/reconcile.go]: Independent of the architectural change being made here, this goroutine could be removed from master with minimal impact on the operation of the Agent.

**Comment by bcwaldon** [comment]
Moving forward with this and cutting a v0.9.1 release.

**Comment by bcwaldon** [comment]
fleet v0.9.1 has been released to the CoreOS Alpha channel. It will be rolled out to Beta and Stable later this week. If anyone who was affected by this bug can validate the fix on Alpha, we would appreciate it.

**Comment by BlueDragonX** [comment]
We've got the update on prod. So far so good!

**Comment by bcwaldon** [comment]
@BlueDragonX thanks for the verification!

**Comment by rufman** [comment]
I'm still seeing the error `failed to load: No such file or directory`

**Comment by rufman** [comment]
running `systemctl daemon-reload`, destroying the service and restarting works (which didn't work most time in v0.9.0)

**Comment by bcwaldon** [comment]
@rufman Would you please share the exact logs and unit files that you are using to reproduce this bug in a new GitHub issue?

**Comment by rufman** [comment]
yes, I double check fleet -version is 0.9.1

**Comment by guruvan** [comment]
@bcwaldon just updated some hosts to 607.0 with 0.9.1 fleet - no dice, reboot hosts with running , units don't start, start units and they just load dead, units consistently need daemon-reload or no such file or directory

Today, I noticed that fleetctl is no longer destroying services all the time from the command line all the time. I had to manually <code>rm /run/fleet/units/the-offending@unit.service<//code> 

this issue has me essentially managing every service by hand and logging directly into the host to use systemctl. My options are narrowing - revert back 2 or 3 previous stable releases, or find another solution - my network has been in a state of rolling outages for weeks now (and it's been constant baby sitting since implementing 607.0 

this is happening with any of over 50 unit files, on 15-20 host network and sanitizing and sifting the logs is a huge chore - please give me exactly what you need so I can find it, otherwise, I'm literally looking for a needle in a hayfield

**Comment by bcwaldon** [comment]
@guruvan I'm more than happy to help debug your issue - could you share any logs and the unit files themselves? Please file a separate issue regarding the fleetctl issue with explicit repro steps and debug logs from fleectl (use the --debug flag).

**Comment by patrickbcullen** [comment]
I am seeing the same bug with 0.9.1 as 0.9.0. Every other destroy/start cycle causes a failure, but only if you use a template and reuse the unit id (i.e. myunit@.service and myunit@1.service).

It should be pretty easy to recreate this on your own. If you cannot let me know.

**Comment by timfallmk** [comment]
@bcwaldon I am consistently seeing the same issue with 0.9.1. I can share any logs and unit files you would like.

**Comment by bcwaldon** [comment]
Just released https://github.com/coreos/fleet/releases/tag/v0.9.2 with another major big fixed. Please reverify unexpected behavior with those binaries. They should be available in Alpha on Thursday.

**Comment by simonvanderveldt** [comment]
I'm not sure if I should create a new issue for this, but is it correct one still has to manually execute fleet steps in the correct order to make dependent unit starting work?
In our case we have a matching monotonic `.timer` unit to a `.service` unit and the only way to get this to work is to use a timer that's based on `OnUnitActiveSec` and has a `MachineOf=app.service` property and then execute the following commands:
```
fleetctl start -no-block app.timer
fleetctl start app.service
```

The `-no-block` is necessary because otherwise fleet will hang indefinitely because it can't load the timer unit because there's no service to schedule it next to.
And when starting the service unit first and then starting the timer the timer doesn't work because it apparently doesn't pick up the service unit's start time if it's started after the service.

This might be related to https://github.com/coreos/fleet/issues/1697

**Comment by dongsupark** [comment]
@simonvanderveldt Thanks for the report. But this PR is already merged, and it has been inactive since 17 months. It's unlikely for anyone to get back to here and read the comment again.
Can you please create a new issue, or just write a comment in https://github.com/coreos/fleet/issues/1697?

**Comment by simonvanderveldt** [comment]
@dongsupark thanks for the response, I'll create a new issue!
