### PR TITLE
ssh: define the list of Key Algorithms of remote hosts before handshake

### LINKED ISSUE #1526: ssh: golang/crypto/ssh prioritizes server's kex algo instead of parsing known_hosts first
Original issue was reported here: https://github.com/coreos/bugs/issues/1186

The problem is that golang ssh implementation compares client's `ServerHostKeyAlgos` and server's `ServerHostKeyAlgos` and chooses first match depending on the order in `supportedHostKeyAlgos` variable:

```go
// supportedKexAlgos specifies the supported host-key algorithms (i.e. methods
// of authenticating servers) in preference order.
var supportedHostKeyAlgos = []string{
        CertAlgoRSAv01, CertAlgoDSAv01, CertAlgoECDSA256v01,
        CertAlgoECDSA384v01, CertAlgoECDSA521v01,

        KeyAlgoECDSA256, KeyAlgoECDSA384, KeyAlgoECDSA521,
        KeyAlgoRSA, KeyAlgoDSA,
}
```

If remote host had `KeyAlgoRSA` key before and it was written into client's `.fleetctl/known_hosts`, then SSH on the remote host was upgraded (i.e. `ecdsa-sha2-nistp256` support was added), then `crypto/ssh` automatically chooses first match: `KeyAlgoECDSA256` and doesn't take into consideration already existing fingerprints. This causes `Failed building SSH client: ssh: handshake failed: host key mismatch` error message on the fleetctl client's side.

### PR DESCRIPTION
**Pull request by tixxdz**
Retrieve remote host Key Algorithms from known_host if they are there
and use them to perform ssh handshake. Otherwise fallback to default
values suggested by remote.

This patch is based from a previous patch written by:
kayrus <kay.diam@gmail.com>

Resolves #1526 and coreos/bugs#1186

### CODE REVIEW

File: ssh/known_hosts.go [hunk 1]
```diff
@@ -87,6 +87,50 @@ func NewHostKeyChecker(m HostKeyManager) *HostKeyChecker {
...
+	_, ok := err.(*os.PathError)
+	if err != nil && !ok {
+		log.Errorf("Failed to read known_hosts file %v: %v", kc.m.String(), err)
+		return nil
+	}
+
+	for pattern, keys := range hostKeys {
+		if !matchHost(remoteAddr, pattern) {
+			remoteIP, err := net.ResolveTCPAddr("tcp", addr)
+			if err != nil {
```
Comment (crawford) [inline ssh/known_hosts.go]: Can we log this error?

File: ssh/known_hosts.go [hunk 2]
```diff
@@ -87,6 +87,50 @@ func NewHostKeyChecker(m HostKeyManager) *HostKeyChecker {
...
+				continue
+			}
+			ipAddr, err := kc.addrToHostPort(remoteIP.String())
+			if err != nil {
```
Comment (crawford) [inline ssh/known_hosts.go]: Same here?

File: ssh/known_hosts.go [hunk 3]
```diff
@@ -87,6 +87,50 @@ func NewHostKeyChecker(m HostKeyManager) *HostKeyChecker {
 	return &HostKeyChecker{m, askToTrustHost}
 }
 
+// Returns public key algorithms of the remote host that are listed
+// inside known_hosts
+func (kc *HostKeyChecker) GetHostKeyAlgorithms(addr string) []string {
+	results := make([]string, 0)
```
Comment (crawford) [inline ssh/known_hosts.go]:
```go
var results []string
```

File: ssh/known_hosts.go [hunk 4]
```diff
@@ -87,6 +87,50 @@ func NewHostKeyChecker(m HostKeyManager) *HostKeyChecker {
...
+			if !matchHost(ipAddr, pattern) {
+				continue
+			}
+		}
+		for _, hostKey := range keys {
+			results = append(results, hostKey.Type())
+		}
+	}
+
+	if len(results) == 0 {
```
Comment (crawford) [inline ssh/known_hosts.go]: With the above declaration, you can omit this check.

**Comment by crawford** [comment]
Without this patch:

```
$  bin/fleetctl --tunnel=ec2-54-153-17-9.us-west-1.compute.amazonaws.com list-machines
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@    WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED!     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
IT IS POSSIBLE THAT SOMEONE IS DOING SOMETHING NASTY!
Someone could be eavesdropping on you right now (man-in-the-middle attack)!
It is also possible that a host key has just been changed.
The fingerprint for the ECDSA key sent by the remote host is
08:b1:9f:a2:50:55:72:1c:df:fa:ae:a1:13:ff:fe:30.
Please contact your system administrator.
Add correct host key in /home/alex/.fleetctl/known_hosts to get rid of this message.
Host key verification failed.
Unable to initialize client: failed initializing SSH client: ssh: handshake failed: host key mismatch
```

With the patch:

```
$ bin/fleetctl --tunnel=ec2-54-153-17-9.us-west-1.compute.amazonaws.com list-machines
MACHINE         IP              METADATA
bb926b38...     172.31.1.5      -
```

LGTM

**Comment by tixxdz** [comment]
@crawford @jonboulle @kayrus  this seems to work and it is a high priority fix, If no one objects I'll merge it tonight. The code doesn't have side effects, on errors we return nil which the upstream ssh library will ignore and fallback to the old behaviour. Thanks!
