### PR TITLE
*: fixed broken template and metadata

### LINKED ISSUE #1514: *: rework "consolidate excessive Hash/Unit requests" PR
We have to rework #1376 PR.

Relates to: #1512, #1446

### PR DESCRIPTION
**Pull request by kayrus**
Resolves #1514

The problem was caused by the [code optimization](https://github.com/coreos/fleet/pull/1376). Before that each unit was stored in its own variable. Then this code was optimized and units became stored in hash map (`getAllUnitsHashMap`). Each hash was assigned to the unit's pointer. And when template unit was checked by `requirements()` function, its content was modified by `values[i] = unitPrintf(v, *uni)` code. Once templated unit was modified, all related units (which have same hash) were modified too, because they are related to one pointer.

Now we don't modify source contents.

### CODE REVIEW

**Comment by jonboulle** [comment]
Great catch, and gross. `requirements()` shouldn't have any side effects. Can you add a unit test for that?

**Comment by kayrus** [comment]
Added test and it has failed. Now, let's apply the fix...

**Comment by kayrus** [comment]
@jonboulle done

File: job/job.go [hunk 1]
```diff
@@ -174,12 +174,17 @@ func (j *Job) requirements() map[string][]string {
 			requirements[key] = make([]string, 0)
 		}
 
-		if uni != nil {
-			for i, v := range values {
-				values[i] = unitPrintf(v, *uni)
+		processedValues := make([]string, len(values))
+
+		for i, v := range values {
```
Comment (tixxdz) [inline job/job.go]: @kayrus thanks for the catch! you can put this inside the same previous loop:
`if uni != nil { processedvalues := make()
     for ... { ...}
     requirements[key] = processedvalues
} else { requirements[key] = values } `

Otherwise it's ok too!

**Comment by tixxdz** [comment]
@kayrus perhaps also improve the commit log of the 4th patch (the fix), same wording as for this PR ? otherwise lgtm. Thank you!

File: job/job.go (hunk 1 above)
Comment (kayrus) [inline job/job.go]: Fixed

**Comment by tixxdz** [comment]
@jonboulle lgtm, thanks!

**Comment by jonboulle** [comment]
LGTM, thanks - but how about reordering a23ce6f after or before 	de4ba7f ?

**Comment by kayrus** [comment]
@jonboulle I suppose we have to show that the issue is covered by tests, and then fix it. so from my point of view the commit order is fine
