### PR TITLE
fleetd: support the version command

### LINKED ISSUE #1210: fleet version gave me a shock
To find out the version of fleet in our current cluster, today I typed in `fleet version`. This is the wrong command, as it must be `fleetctl version` or `fleet -version`.

Fleet seem to have started and then wanted to remove units (which I guess failed due to running as `coreos`, not `root`):

```
$ fleet version
INFO fleet.go:58: Starting fleetd version 0.9.1
INFO fleet.go:162: No provided or default config file found - proceeding without
INFO server.go:153: Establishing etcd connectivity
INFO server.go:164: Starting server components
INFO manager.go:262: Writing systemd unit companyd-presence@2.service (1154b)
INFO reconcile.go:313: AgentReconciler task failed: type=LoadUnit job=companyd-presence@2.service reason="unit scheduled here but not loaded" err=open /run/fleet/units/companyd-presence@2.service: permission denied
^CINFO fleet.go:107: Gracefully shutting down
INFO client.go:291: Failed getting response from http://localhost:4001/: cancelled
ERROR event.go:107: etcd watcher {Watch /_coreos.com/fleet/job} returned error: cancelled
INFO client.go:291: Failed getting response from http://localhost:4001/: cancelled
ERROR event.go:107: etcd watcher {Watch /_coreos.com/fleet/job} returned error: cancelled
^C^C^C^C^CERROR manager.go:147: Failed to trigger systemd unit cluster-backup.service stop: Interactive authentication required.
INFO manager.go:275: Removing systemd unit cluster-backup.service
```

Also I had to use `kill -9` from another shell, as `Ctrl + C` didn't work.

Thus I have the following questions?
1) Can we make `fleet version` work too (consistency with `fleetctl`) ?
2) Is hitting `Ctrl+C` supposed to work? It says `INFO fleet.go:107: Gracefully shutting down` after the first time, but doesn't stop.
3) Is intended that I can run multiple agents on the same machine?

### PR DESCRIPTION
**Pull request by wuqixuan**
Now support "fleetd version" and "fleetd --version"

Fixes #1210

### CODE REVIEW

**Comment by wuqixuan** [comment]
Hi @bcwaldon , This patch has been builded and tested in my pc, but I don't know why it fails "The Travis CI build failed ". Can you help to give some information? Thanks a lot.

File: fleetd/fleet.go [hunk 1]
```diff
@@ -48,7 +48,9 @@ func main() {
 		os.Exit(1)
 	}
 
-	if *printVersion {
+	var args = userset.Args()
```
Comment (bcwaldon) [inline fleetd/fleet.go]: This isn't really necessary, just `userset.Args()[0] == "version"` below

Comment (wuqixuan) [inline fleetd/fleet.go]: Yes, you are right, I have modified as per your suggestion. Please let me know whether there is any other issue or not.

**Comment by bcwaldon** [comment]
LGTM

**Comment by marineam** [comment]
This change is triggering a panic:

```
May 08 23:39:50 86c4b2e1 fleetd[584]: panic: runtime error: index out of range
May 08 23:39:50 86c4b2e1 fleetd[584]: goroutine 1 [running]:
May 08 23:39:50 86c4b2e1 fleetd[584]: main.main()
May 08 23:39:50 86c4b2e1 fleetd[584]: /home/marineam/go/src/github.com/coreos/fleet/gopath/src/github.com/coreos/fleet/fleetd/fleet.go:51 +0x1433
May 08 23:39:50 86c4b2e1 fleetd[584]: goroutine 2 [runnable]:
May 08 23:39:50 86c4b2e1 fleetd[584]: runtime.forcegchelper()
May 08 23:39:50 86c4b2e1 fleetd[584]: /usr/lib/go/src/runtime/proc.go:90
May 08 23:39:50 86c4b2e1 fleetd[584]: runtime.goexit()
May 08 23:39:50 86c4b2e1 fleetd[584]: /usr/lib/go/src/runtime/asm_amd64.s:2232 +0x1
May 08 23:39:50 86c4b2e1 fleetd[584]: goroutine 3 [runnable]:
May 08 23:39:50 86c4b2e1 fleetd[584]: runtime.bgsweep()
May 08 23:39:50 86c4b2e1 fleetd[584]: /usr/lib/go/src/runtime/mgc0.go:82
May 08 23:39:50 86c4b2e1 fleetd[584]: runtime.goexit()
May 08 23:39:50 86c4b2e1 fleetd[584]: /usr/lib/go/src/runtime/asm_amd64.s:2232 +0x1
May 08 23:39:50 86c4b2e1 fleetd[584]: /usr/lib/go/src/runtime/mgc0.go:82
May 08 23:39:50 86c4b2e1 fleetd[584]: runtime.goexit()
May 08 23:39:50 86c4b2e1 fleetd[584]: /usr/lib/go/src/runtime/asm_amd64.s:2232 +0x1
May 08 23:39:50 86c4b2e1 fleetd[584]: goroutine 4 [runnable]:
May 08 23:39:50 86c4b2e1 fleetd[584]: runtime.runfinq()
May 08 23:39:50 86c4b2e1 fleetd[584]: /usr/lib/go/src/runtime/malloc.go:712
May 08 23:39:50 86c4b2e1 fleetd[584]: runtime.goexit()
May 08 23:39:50 86c4b2e1 fleetd[584]: /usr/lib/go/src/runtime/asm_amd64.s:2232 +0x1
May 08 23:39:50 86c4b2e1 fleetd[584]: goroutine 5 [runnable]:
May 08 23:39:50 86c4b2e1 fleetd[584]: os/signal.loop()
May 08 23:39:50 86c4b2e1 fleetd[584]: /usr/lib/go/src/os/signal/signal_unix.go:19
May 08 23:39:50 86c4b2e1 fleetd[584]: created by os/signal.init·1
May 08 23:39:50 86c4b2e1 fleetd[584]: /usr/lib/go/src/os/signal/signal_unix.go:27 +0x35
```
